# Setup
title: 'hacker tools'
url: https://edgfb-753.github.io/hacker-tools

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true
# safe: true # breaks local rendering if enabled
timezone: America/New_York

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock